config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :posts do
  resources :comments
end


root 'posts#index'

get '/about'  ,to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments , dependent: :destroy
    validates :title, presence: true , length: { minimum: 5 }
    validates :body , presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params.require(:comment).permit(:name , :body))
        redirect_to post_path(@post)

    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
        
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post , only: [:show , :edit , :update , :destroy]
    def index 
        @posts = Post.all.order("created_at DESC")
    end
    def show
        
    end

    def new 
        @post = Post.new
    end

    def create 
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end

    end

    def edit 
    
    end

    def update

        if (@post.update(post_params))
            redirect_to @post 
        else
            render 'edit'
        end

    end

    def destroy 
        @post.destroy
        redirect_to root_path
    end
        






    private

        def post_params
            params.require(:post).permit(:title,:body)
        end

        def find_post
            @post = Post.find(params[:id])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comment/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
        <% @post.comments.each do |comment| %>
            <p class="comment_name"><strong><%= comment.name %></strong> 
            | <%= link_to 'Delete' , [comment.post , comment],method: :delete  ,
            data: {confirm: 'Are you sure'}  %>
            </p> <br>
            <p class="comment_body"><%= comment.body %></p>
            <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago </p>
        <%end%>
    </div>
</div>

app/views/comment/_form.html.erb
<%= form_with(model:  [@post , @post.comments.build] ,local: true) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name%>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    <br>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico.png'%>
    
  </head>

  <body>
    <div id="sidebar">
		  <ul>
			  <li class="category"><%= link_to "Tumblr", root_path %></li>
			  <li><%= link_to "Posts", root_path %></li>
			  <li><%= link_to  "About", about_path %></li>
		  </ul>

			<p class="sign_in">User Login</p>
    </div>
	

  <div id="main_content">
		<div id="header">
			<% if current_page?(root_path)%>	
		  		<p>Post Feed</p>
		  	<% elsif current_page?(about_path)%>
			  	<p>My Site</p>
			<% else %>
				<%= link_to  "Back To Post Feed", root_path %>
			<% end%>
			<div class="buttons">
				<button class="button"><%= link_to "Make Post", new_post_path %></button>
				<button class="button">Logout</button>
			</div>

	</div>	
		
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>

	</div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper"> 
    <div id="profile_image">
         <%= image_tag  "profile.jpeg" %>
    </div>

    <div id="content">
        <h1>It's Mr. Myousry </h1>
        <p>Facebook checks your friends list and looks for mutual friends. These mutual friends are shown as suggestions on your timeline.

        For example, your siblings friends could be people you know. So they will be shown as “friend suggestion” on your timeline.

        But Facebook is not accurate and most of the times ends up showing random people you don’t know in friend’s suggestions.
        </p>
    </div>
</div>

app/views/posts/_form.html.erb
    <%= form_for @post do |f| %>
        <% if @post.errors.any? %>
            <div id="errors">
                <h2> <%= pluralize(@post.errors.count, "error")%> stopped this post from saving </h2>
                <ul>
                    <%= @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <%end%>
                </ul>
            </div>
        <%end%>
        <p>
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </p>

        <p>
            <%= f.label :body %><br>
            <%= f.text_area :body %>
        </p>
    
        <p>
            <%= f.submit %>
        </p>    
    <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">  
    <h1>Edit <h2><%= @post.title%></h2></h1>
    <%= render  "form" %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
        <h2 class="title"><%= link_to  post.title, post_path(post)%> 
        <p class="body"><%= truncate(post.body, length:100 ) %> </p>
        <p class="date"> <%= time_ago_in_words(post.created_at)%> ago |
        <%= link_to 'Edit' , edit_post_path(post)%> |
        <%= link_to 'Delete' , post_path(post), method: :delete,data: {confirm: 'Are you sure'} %>
        </p>
    </div>
<%end%>

app/views/posts/new.html.erb
 <div id="page_wrapper">  
    <h1>Create New Post</h1>
    <%= render  "form" %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%= @post.title%> 
    </h1>

    <p class="date">
        Submitted <%= time_ago_in_words(@post.created_at) %> ago | 
        <%= link_to 'Edit' , edit_post_path(@post)%> |
        <%= link_to 'Delete' , post_path(@post), method: :delete,data: {confirm: 'Are you sure'}%>
    </p>

    <p class="body">
        <%= @post.body %>
    </p>
    <% #comments %>

    <div id="comments">
        <h2><%= @post.comments.count%> Comments</h2>
        <%= render 'comment/comment' %> 
        <h3> Add Comment </h3>
        <%= render 'comment/form' %>
    </div>
</div>